"use strict";
const readline = require("readline");
const { runTask } = require("../gui-run");
const fs = require("fs");
const { editSettings } = require("../gui-settings");
const { handleCommand } = require("../gui-commands");
const { listSessions, getSession } = require("../../runtime/sessions");
const { runPipeline } = require("../../pipeline/loop");
const { sessionResumeContext, restoreSession } = require("../../runtime/resume");
const { requireEntitlement } = require("../login-screen");
function printHeader() { if (process.env.MINITOK_NO_COLOR !== "1" && process.stdout.isTTY) console.clear(); const line = process.env.MINITOK_ASCII === "1" ? "--------" : "────────"; console.log(`minitok\nSessions\n${line}`); }
async function startGui(options = {}) {
  const nonTty = !process.stdin.isTTY || !process.stdout.isTTY;
  if (nonTty && !options.task && !process.env.MINITOK_TASK) throw new Error("Non-TTY usage requires --task or MINITOK_TASK");
  await requireEntitlement({ server: options.server, plain: options.plain, ascii: options.ascii });
  if (process.stdin.isTTY && process.stdout.isTTY && options.fullscreen !== false) return require("../fullscreen-gui").createFullscreenGui(options);
  const repo = options.repo || process.cwd(); if (nonTty) { const task = options.task || process.env.MINITOK_TASK; const capture = options.json === true; const originalLog = console.log; const originalInfo = console.info; const originalWarn = console.warn; if (capture) { console.log = (...values) => { }; console.info = (...values) => { }; console.warn = (...values) => { }; } try { const result = await runPipeline(task, { repoRoot: repo, autoAccept: options.autoAccept === true }); if (options.json === true) originalLog(JSON.stringify({ command: "gui", status: result.success ? "completed" : "failed", success: result.success === true, run_id: result.run_id || null, cycles: result.cycles?.length || 0 })); process.exitCode = result.success ? 0 : 1; return result; } catch (error) { if (options.json === true) { originalLog(JSON.stringify({ command: "gui", status: "failed", success: false, error: error.message })); process.exitCode = 1; return { success: false, error: error.message }; } throw error; } finally { if (capture) { console.log = originalLog; console.info = originalInfo; console.warn = originalWarn; } } }
  printHeader(); const renderSessions = () => { const width = process.stdout.columns || 80; listSessions(repo).slice(0, 8).forEach((s, i) => { const label = s.task || s.run_id; console.log(width < 70 ? `${i + 1}. ${(s.status || s.outcome || "unknown").slice(0, 12)} ${label.slice(0, 32)}` : `${i + 1}. ${s.status || s.outcome || "unknown"} ${label}`); }); }; renderSessions(); process.stdout.on("resize", () => { printHeader(); renderSessions(); }); console.log("\nEnter task, :help, or :q");
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout, prompt: "minitok> " }); const state = { activeAbort: undefined, approvalActive: false }; rl.prompt();
  for await (const line of rl) { const input = line.trim(); if ((state.activeAbort || state.approvalActive) && ![":status", ":cancel", ":q", ":quit", "exit"].includes(input)) { console.log("Run active. Use :status or :cancel."); rl.prompt(); continue; } if ([":q", ":quit", "exit"].includes(input)) break; if (input === ":help") { console.log(":sessions :resume <id> :status :settings :mcp :models :diff <id> [--full] :restore <id> [--preview|--apply] :cancel :multiline :q"); rl.prompt(); continue; } if (input === ":settings") { await editSettings(repo, rl); rl.prompt(); continue; } if (input === ":status") { console.log(state.activeAbort ? "Run: active" : "Run: idle"); rl.prompt(); continue; } if (input === ":cancel") { state.activeAbort?.abort(); rl.prompt(); continue; } if (input.startsWith(":resume ")) { const key = input.slice(8).trim(); const sessions = listSessions(repo); const s = sessions[Number(key) - 1] || getSession(repo, key); if (!s?.task) console.log("Session not found"); else { console.log(sessionResumeContext(s)); const checkpoint = s.checkpoint_path || s.checkpointPath; if (checkpoint && fs.existsSync(`${checkpoint}/working-tree.patch`)) { const answer = await new Promise(resolve => rl.question("Restore checkpoint before resume? [y/n] ", value => resolve(value.trim().toLowerCase().startsWith("y")))); if (answer) { try { console.log(JSON.stringify(restoreSession(repo, s), null, 2)); } catch (error) { console.log(`Restore failed: ${error.message}`); continue; } } } await runTask(`${sessionResumeContext(s)}\n\nContinue task: ${s.task}`, repo, rl, state); } rl.prompt(); continue; } if (handleCommand(input, { repo, rl, state })) { rl.prompt(); continue; } if (input === ":multiline") { const lines = []; console.log("Enter lines; finish with :end"); for await (const part of rl) { if (part.trim() === ":end") break; lines.push(part); } await runTask(lines.join("\n"), repo, rl, state); rl.prompt(); continue; } if (input) await runTask(input, repo, rl, state); else rl.prompt(); }
  rl.close();
}
function register(program) { program.command("gui").alias("ui").option("--repo <path>").option("--task <task>").option("--server <url>").option("--auto-accept", "accept proposed changes non-interactively").option("--json", "output one machine-readable JSON result in non-TTY mode").option("--plain", "disable ANSI output").option("--ascii", "use ASCII output").option("--no-fullscreen", "use legacy readline mode").description("Open the minitok terminal interface").action(startGui); }
module.exports = { register, startGui, runTask };
